# -*- coding: utf-8 -*-
"""Iris_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mFKsXx7Nns1zmHtcrR-l_cIW0fKUcBT4

# TITANIC SURVIVAL PREDICTION
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

import warnings
warnings.filterwarnings('ignore')

print("TASK 1 - TITANIC SURVIVAL PREDICTION")

print("\nStep 1: Libraries imported!")

df = pd.read_csv('/content/Titanic-Dataset.csv')

print(f"Rows: {df.shape[0]}  |  Columns: {df.shape[1]}")

task_columns = ['Survived', 'Pclass', 'Sex', 'Age', 'Fare', 'Cabin']
df = df[task_columns].copy()

print("\nTask-specific columns selected:")
print("  Survived - Target (what we predict)")
print("  Pclass   - Ticket Class (1st / 2nd / 3rd)")
print("  Sex      - Gender (male / female)")
print("  Age      - Age of passenger")
print(" Fare      - Ticket fare amount")
print(" Cabin     - Cabin number")

print(f"\nData after selecting task columns:")
print(df.head(10))
print(f"\nMissing values:")
print(df.isnull().sum())

print("\nGenerating charts for task columns...")

fig, axes = plt.subplots(3, 2, figsize=(14, 16))
fig.suptitle('Titanic Survival Prediction - Task 1 Analysis',
             fontsize=16, fontweight='bold')
survival_counts = df['Survived'].value_counts().sort_index()
axes[0,0].bar(['Not Survived (0)', 'Survived (1)'],
               survival_counts.values,
               color=['#e74c3c', '#2ecc71'], edgecolor='white', width=0.5)
axes[0,0].set_title('Survival Count\n(Task Target Variable)', fontweight='bold')
axes[0,0].set_ylabel('Number of Passengers')
for i, v in enumerate(survival_counts.values):
    axes[0,0].text(i, v+5, str(v), ha='center', fontweight='bold', fontsize=12)

gender_surv = df.groupby(['Sex', 'Survived']).size().unstack(fill_value=0)
gender_surv.plot(kind='bar', ax=axes[0,1],
                 color=['#e74c3c', '#2ecc71'], edgecolor='white', rot=0)
axes[0,1].set_title('Survival by Gender\n(Task: gender feature)', fontweight='bold')
axes[0,1].set_xlabel('Gender')
axes[0,1].set_ylabel('Count')
axes[0,1].legend(['Not Survived', 'Survived'])

pclass_surv = df.groupby(['Pclass', 'Survived']).size().unstack(fill_value=0)
pclass_surv.plot(kind='bar', ax=axes[1,0],
                 color=['#e74c3c', '#2ecc71'], edgecolor='white', rot=0)
axes[1,0].set_title('Survival by Ticket Class\n(Task: ticket class feature)',
                     fontweight='bold')
axes[1,0].set_xlabel('Ticket Class (1=First, 2=Second, 3=Third)')
axes[1,0].set_ylabel('Count')
axes[1,0].legend(['Not Survived', 'Survived'])

df[df['Survived']==0]['Age'].dropna().hist(
    bins=25, ax=axes[1,1], alpha=0.6, color='#e74c3c', label='Not Survived')
df[df['Survived']==1]['Age'].dropna().hist(
    bins=25, ax=axes[1,1], alpha=0.6, color='#2ecc71', label='Survived')
axes[1,1].set_title('Survival by Age\n(Task: age feature)', fontweight='bold')
axes[1,1].set_xlabel('Age (years)')
axes[1,1].set_ylabel('Count')
axes[1,1].legend()

df[df['Survived']==0]['Fare'].hist(
    bins=25, ax=axes[2,0], alpha=0.6, color='#e74c3c', label='Not Survived')
df[df['Survived']==1]['Fare'].hist(
    bins=25, ax=axes[2,0], alpha=0.6, color='#2ecc71', label='Survived')
axes[2,0].set_title('Survival by Fare\n(Task: fare feature)', fontweight='bold')
axes[2,0].set_xlabel('Fare ($)')
axes[2,0].set_ylabel('Count')
axes[2,0].legend()

df['Has_Cabin'] = df['Cabin'].apply(lambda x: 'Has Cabin' if pd.notna(x) else 'No Cabin')
cabin_surv = df.groupby(['Has_Cabin', 'Survived']).size().unstack(fill_value=0)
cabin_surv.plot(kind='bar', ax=axes[2,1],
                color=['#e74c3c', '#2ecc71'], edgecolor='white', rot=0)
axes[2,1].set_title('Survival by Cabin\n(Task: cabin feature)', fontweight='bold')
axes[2,1].set_xlabel('Cabin Status')
axes[2,1].set_ylabel('Count')
axes[2,1].legend(['Not Survived', 'Survived'])

plt.tight_layout()
plt.savefig('titanic_task1_eda.png', dpi=150, bbox_inches='tight')
plt.show()
print("Charts saved as titanic_task1_eda.png!")

df['Age'].fillna(df['Age'].median(), inplace=True)
print(f"Age    : missing values filled with median ({df['Age'].median():.1f})")
df['Fare'].fillna(df['Fare'].median(), inplace=True)
print(f"Fare   : missing values filled with median")
df['Cabin'] = df['Cabin'].apply(lambda x: 1 if pd.notna(x) else 0)
print(f" Cabin  : converted → 1=Has Cabin, 0=No Cabin")
df['Sex'] = df['Sex'].map({'male': 1, 'female': 0})
print(f"Sex    : encoded → male=1, female=0")
print(f"\nCleaned dataset shape: {df.shape}")
print(f" Missing values left  : {df.isnull().sum().sum()}")
print("\nFinal preprocessed data:")
print(df.head(10))

X = df[['Pclass', 'Sex', 'Age', 'Fare', 'Cabin']]
y = df['Survived']

print("\nFeatures (X) — from task description:")
print("  Pclass  → Ticket Class")
print("  Sex     → Gender")
print("  Age     → Age")
print("  Fare    → Fare")
print("  Cabin   → Cabin (1=has, 0=no)")
print("\nTarget (y):")
print("  Survived → 0=Did Not Survive, 1=Survived")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

print(f"\nTraining samples : {X_train.shape[0]}")
print(f"Testing  samples : {X_test.shape[0]}")

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
accuracy    = accuracy_score(y_test, predictions)

print(f"\n Model  : Random Forest Classifier")
print(f"Accuracy: {accuracy*100:.2f}%")

print("\nClassification Report:")
print(classification_report(y_test, predictions,
      target_names=['Not Survived', 'Survived']))

cm = confusion_matrix(y_test, predictions)
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Not Survived', 'Survived'],
            yticklabels=['Not Survived', 'Survived'],
            annot_kws={"size": 16, "weight": "bold"})
plt.title('Confusion Matrix - Titanic Survival Prediction',
          fontsize=13, fontweight='bold')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.savefig('titanic_confusion_matrix.png', dpi=150)
plt.show()

tn, fp, fn, tp = cm.ravel()
print(f"\nCorrectly predicted SURVIVED    : {tp}")
print(f"Correctly predicted NOT SURVIVED: {tn}")
print(f"Wrong predictions               : {fp+fn}")

feat_imp = pd.Series(model.feature_importances_,
                     index=['Ticket Class', 'Gender',
                            'Age', 'Fare', 'Cabin']
                     ).sort_values(ascending=False)

plt.figure(figsize=(8, 5))
feat_imp.plot(kind='bar', color='#3498db', edgecolor='white')
plt.title('Feature Importance - Which feature affects survival most?',
          fontsize=12, fontweight='bold')
plt.ylabel('Importance Score')
plt.xticks(rotation=30)
plt.tight_layout()
plt.savefig('titanic_feature_importance.png', dpi=150)
plt.show()

print("\nFeature Importance:")
for feat, score in feat_imp.items():
    bar = '|' * int(score * 50)
    print(f"  {feat:<15}: {score:.4f}  {bar}")

new_passengers = pd.DataFrame({
    'Pclass': [1,   3,   2,   1  ],
    'Sex'   : [0,   1,   1,   0  ],
    'Age'   : [25,  35,  18,  60 ],
    'Fare'  : [72,  15,  13,  90 ],
    'Cabin' : [1,   0,   0,   1  ],
})

descriptions = [
    "Female | Age 25 | 1st Class | Has Cabin",
    "Male   | Age 35 | 3rd Class | No Cabin",
    "Male   | Age 18 | 2nd Class | No Cabin",
    "Female | Age 60 | 1st Class | Has Cabin",
]

preds = model.predict(new_passengers)
probs = model.predict_proba(new_passengers)

print(f"\n{'Passenger':<42} {'Result':<20} Survival%")
print("-" * 75)
for desc, pred, prob in zip(descriptions, preds, probs):
    result = "SURVIVED" if pred==1 else " NOT SURVIVED"
    print(f"{desc:<42} {result:<20} {prob[1]*100:.1f}%")
